/**
 * Static fallback data for categories, products and brands.
 * Used when the database has no data (e.g. fresh Supabase instance).
 */

export const STATIC_CATEGORIES = [
  {
    id: "cat-1",
    slug: "contadoras-billetes",
    name: "Contadoras de Billetes",
    description:
      "Máquinas profesionales de conteo de billetes para todos los volúmenes de operación. Detección de falsificación por UV, MG, IR y 2D.",
    icon: "Banknote",
    order: 1,
    image: null,
    _count: { products: 6 },
  },
  {
    id: "cat-2",
    slug: "contadoras-monedas",
    name: "Contadoras de Monedas",
    description:
      "Equipos de conteo y clasificación de monedas de alta velocidad. Soportan múltiples divisas incluyendo sol peruano, dólar americano y euro.",
    icon: "Coins",
    order: 2,
    image: null,
    _count: { products: 3 },
  },
  {
    id: "cat-3",
    slug: "clasificadoras-billetes",
    name: "Clasificadoras de Billetes",
    description:
      "Máquinas de clasificación y discriminación de billetes por denominación y orientación. Reconocimiento por imagen CIS.",
    icon: "Layers",
    order: 3,
    image: null,
    _count: { products: 3 },
  },
  {
    id: "cat-4",
    slug: "detectores-falsificacion",
    name: "Detectores de Falsificación",
    description:
      "Detectores de billetes falsos con tecnología multifunción: luz ultravioleta (UV), lámpara magnética (MG), infrarrojo (IR).",
    icon: "ShieldCheck",
    order: 4,
    image: null,
    _count: { products: 2 },
  },
  {
    id: "cat-5",
    slug: "accesorios-suministros",
    name: "Accesorios y Suministros",
    description:
      "Kit de mantenimiento, cintas transportadoras, bolsas de depósito seguras y consumibles para equipos de procesamiento de efectivo.",
    icon: "Settings",
    order: 5,
    image: null,
    _count: { products: 2 },
  },
];

export const STATIC_BRANDS = [
  {
    id: "brand-1",
    slug: "glory",
    name: "Glory Global",
    logo: null,
    description: "Líder mundial en soluciones de procesamiento de efectivo.",
    website: "https://www.glory-global.com",
    order: 1,
    _count: { products: 4 },
  },
  {
    id: "brand-2",
    slug: "cashscan",
    name: "CashScan",
    logo: null,
    description: "Equipos de conteo y detección de billetes con alta tecnología.",
    website: "",
    order: 2,
    _count: { products: 3 },
  },
  {
    id: "brand-3",
    slug: "hyundai",
    name: "Hyundai",
    logo: null,
    description: "Contadoras de billetes confiables para todo tipo de negocio.",
    website: "",
    order: 3,
    _count: { products: 2 },
  },
  {
    id: "brand-4",
    slug: "royal-sovereign",
    name: "Royal Sovereign",
    logo: null,
    description: "Equipos de conteo de billetes y monedas accesibles y funcionales.",
    website: "",
    order: 4,
    _count: { products: 2 },
  },
];

export const STATIC_PRODUCTS = [
  // ─── CONTADORAS DE BILLETES ───
  {
    id: "prod-1",
    slug: "glory-gfb-800",
    name: "Glory GFB-800",
    summary:
      "Contadora de billetes profesional con detección UV, MG e IR. Ideal para bancos y empresas con alto volumen de efectivo. Velocidad de hasta 1.800 billetes/minuto.",
    sku: "GLR-GFB800",
    price: null,
    currency: "PEN",
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    category: { slug: "contadoras-billetes", name: "Contadoras de Billetes" },
    brand: { slug: "glory", name: "Glory Global" },
    images: [],
  },
  {
    id: "prod-2",
    slug: "glory-rbc-4500",
    name: "Glory RBC-4500",
    summary:
      "Contadora de billetes de alto rendimiento con detección 2D, UV, MG e IR. Hopper de alta capacidad, pantalla LCD intuitiva. Para casas de cambio y retail.",
    sku: "GLR-RBC4500",
    price: null,
    currency: "PEN",
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    category: { slug: "contadoras-billetes", name: "Contadoras de Billetes" },
    brand: { slug: "glory", name: "Glory Global" },
    images: [],
  },
  {
    id: "prod-3",
    slug: "cashscan-cs-310",
    name: "CashScan CS-310",
    summary:
      "Contadora de billetes compacta con detección UV y MG. Perfecta para pequeños comercios, oficinas y puntos de venta con movimiento moderado.",
    sku: "CSH-CS310",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    category: { slug: "contadoras-billetes", name: "Contadoras de Billetes" },
    brand: { slug: "cashscan", name: "CashScan" },
    images: [],
  },
  {
    id: "prod-4",
    slug: "cashscan-cs-520",
    name: "CashScan CS-520",
    summary:
      "Contadora profesional con detección UV, MG, IR y doble CIS. Pantalla LCD, conteo por lotes y función de acumulación. Para empresas y financieras.",
    sku: "CSH-CS520",
    price: null,
    currency: "PEN",
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    category: { slug: "contadoras-billetes", name: "Contadoras de Billetes" },
    brand: { slug: "cashscan", name: "CashScan" },
    images: [],
  },
  {
    id: "prod-5",
    slug: "hyundai-hb-1200",
    name: "Hyundai HB-1200",
    summary:
      "Contadora de billetes económica con detección UV básica. Velocidad de 1.000 billetes/minuto. Ideal para tiendas, farmacias y pequeños negocios.",
    sku: "HYU-HB1200",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    category: { slug: "contadoras-billetes", name: "Contadoras de Billetes" },
    brand: { slug: "hyundai", name: "Hyundai" },
    images: [],
  },
  {
    id: "prod-6",
    slug: "royal-sovereign-rbc-100",
    name: "Royal Sovereign RBC-100",
    summary:
      "Contadora de billetes compacta y portátil. Detección UV, conteo rápido y función de batch. Perfecta para uso en oficinas y comercios pequeños.",
    sku: "RS-RBC100",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    category: { slug: "contadoras-billetes", name: "Contadoras de Billetes" },
    brand: { slug: "royal-sovereign", name: "Royal Sovereign" },
    images: [],
  },
  // ─── CONTADORAS DE MONEDAS ───
  {
    id: "prod-7",
    slug: "glory-cn-700",
    name: "Glory CN-700",
    summary:
      "Contadora de monedas de alta velocidad con clasificación por denominación. Soporta sol peruano, dólar y euro. Para bancos y supermercados.",
    sku: "GLR-CN700",
    price: null,
    currency: "PEN",
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    category: { slug: "contadoras-monedas", name: "Contadoras de Monedas" },
    brand: { slug: "glory", name: "Glory Global" },
    images: [],
  },
  {
    id: "prod-8",
    slug: "cashscan-cc-200",
    name: "CashScan CC-200",
    summary:
      "Contadora de monedas compacta con pantalla LCD. Cuenta hasta 300 monedas por minuto. Ideal para estacionamientos, peajes y retail.",
    sku: "CSH-CC200",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    category: { slug: "contadoras-monedas", name: "Contadoras de Monedas" },
    brand: { slug: "cashscan", name: "CashScan" },
    images: [],
  },
  {
    id: "prod-9",
    slug: "royal-sovereign-qc-100",
    name: "Royal Sovereign QC-100",
    summary:
      "Contadora de monedas accesible y fácil de usar. Función de conteo por lotes y parada automática. Para pequeños comercios y empresas de transporte.",
    sku: "RS-QC100",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    category: { slug: "contadoras-monedas", name: "Contadoras de Monedas" },
    brand: { slug: "royal-sovereign", name: "Royal Sovereign" },
    images: [],
  },
  // ─── CLASIFICADORAS DE BILLETES ───
  {
    id: "prod-10",
    slug: "glory-gfs-220",
    name: "Glory GFS-220",
    summary:
      "Clasificadora de billetes con reconocimiento CIS de alta resolución. Clasifica por denominación y orientación. Detección de falsificación 2D avanzada.",
    sku: "GLR-GFS220",
    price: null,
    currency: "PEN",
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    category: { slug: "clasificadoras-billetes", name: "Clasificadoras de Billetes" },
    brand: { slug: "glory", name: "Glory Global" },
    images: [],
  },
  {
    id: "prod-11",
    slug: "glory-gfs-110",
    name: "Glory GFS-110",
    summary:
      "Clasificadora de billetes compacta para operaciones medianas. Reconocimiento por imagen, detección UV, MG, IR. Ideal para bancos y procesadoras.",
    sku: "GLR-GFS110",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    category: { slug: "clasificadoras-billetes", name: "Clasificadoras de Billetes" },
    brand: { slug: "glory", name: "Glory Global" },
    images: [],
  },
  {
    id: "prod-12",
    slug: "cashscan-cds-300",
    name: "CashScan CDS-300",
    summary:
      "Clasificadora y discriminadora de billetes con doble sensor CIS. Clasifica por valor y orientación con alta precisión.",
    sku: "CSH-CDS300",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    category: { slug: "clasificadoras-billetes", name: "Clasificadoras de Billetes" },
    brand: { slug: "cashscan", name: "CashScan" },
    images: [],
  },
  // ─── DETECTORES DE FALSIFICACIÓN ───
  {
    id: "prod-13",
    slug: "detector-uv-mg-5en1",
    name: "Detector UV/MG 5 en 1",
    summary:
      "Detector multifunción de escritorio con luz UV, lámpara magnética, infrarrojo, luz blanca y lupa de aumento. Para billetes peruanos y dólares.",
    sku: "DET-5IN1",
    price: null,
    currency: "PEN",
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    category: { slug: "detectores-falsificacion", name: "Detectores de Falsificación" },
    brand: { slug: "cashscan", name: "CashScan" },
    images: [],
  },
  {
    id: "prod-14",
    slug: "detector-portatil-uv-pro",
    name: "Detector Portátil UV Pro",
    summary:
      "Detector portátil de billetes falsos con lámpara ultravioleta de alta potencia. Compacto, funciona con pilas. Para verificación rápida en campo.",
    sku: "DET-UVP",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    category: { slug: "detectores-falsificacion", name: "Detectores de Falsificación" },
    brand: { slug: "hyundai", name: "Hyundai" },
    images: [],
  },
  // ─── ACCESORIOS Y SUMINISTROS ───
  {
    id: "prod-15",
    slug: "kit-mantenimiento-preventivo",
    name: "Kit de Mantenimiento Preventivo",
    summary:
      "Kit completo de limpieza y mantenimiento para contadoras de billetes. Incluye hisopos, alcohol isopropílico, escobillas y guía de mantenimiento.",
    sku: "ACC-KITMANT",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    category: { slug: "accesorios-suministros", name: "Accesorios y Suministros" },
    brand: { slug: "glory", name: "Glory Global" },
    images: [],
  },
  {
    id: "prod-16",
    slug: "cinta-transportadora-universal",
    name: "Cinta Transportadora Universal",
    summary:
      "Cinta de reemplazo para contadoras de billetes. Material resistente de alta durabilidad. Compatible con principales marcas y modelos.",
    sku: "ACC-CINTA01",
    price: null,
    currency: "PEN",
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    category: { slug: "accesorios-suministros", name: "Accesorios y Suministros" },
    brand: { slug: "glory", name: "Glory Global" },
    images: [],
  },
];